version: '3.8'

services:
  host-client:
    container_name: host-client-prod
    image: host-client-prod:latest
    build:
      context: ./host-client
      dockerfile: Dockerfile.prod
      target: production
    env_file:
      - ./host-client/.env.production
    ports:
      - "3001:3000"
    volumes:
      - /app/node_modules
      - /app/.next
      
  auth: 
    container_name: auth-dev
    image: auth-dev:latest
    build:
      context: ./auth
      dockerfile: Dockerfile.dev
    env_file:
      - ./auth/.env.development
    ports:
      - "3001:3000" 
    volumes:
      - /app/node_modules
    depends_on:
      - authDb
    networks:
      - auth-network
  
  authDb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - authMongoDb:/data/db
    networks:
      - auth-network

volumes:
  authMongoDb: {}

networks:
  auth-network:
    driver: bridge
