version: '3.8'

services:
  host-client:
    container_name: host-client-prod
    image: host-client-prod:latest
    build:
      context: ./host-client
      dockerfile: Dockerfile.prod
      target: production
    env_file:
      - ./host-client/.env.prod
    ports:
      - "3001:3000"
    volumes:
      - /app/node_modules
      - /app/.next
